name: "🛠️ 기타 작업 (Chore)"
description: "빌드, 설정, 도구 등 기타 작업"
title: "[CHORE] "
labels: ["chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: "작업 내용"
      description: "어떤 작업을 진행할 예정인가요?"
      placeholder: "예: CI/CD 파이프라인 설정, 의존성 업데이트, 코드 포맷팅 등"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      description: "작업의 우선순위를 선택해주세요"
      options:
        - "🔴 높음"
        - "🟡 보통"
        - "🟢 낮음"

  - type: textarea
    id: additional
    attributes:
      label: "추가 정보"
      description: "관련 문서, 참고 자료, 특별한 요구사항 등"
      placeholder: "관련 문서 링크, 참고할 자료, 특별한 요구사항 등을 작성해주세요" 
      