name: "🐛 버그 수정 (Fix)"
description: "발견한 버그 수정"
title: "[FIX] "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "버그 설명"
      description: "어떤 버그인지 명확하게 설명해주세요"
      placeholder: "예: 사용자 로그인 시 500 에러가 발생한다"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "심각도"
      description: "버그의 심각도를 선택해주세요"
      options:
        - "🔴 치명적"
        - "🟠 높음"
        - "🟡 보통"
        - "🟢 낮음"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "예상 동작"
      description: "정상적으로 동작했을 때의 결과를 작성해주세요"
      placeholder: "잘못된 로그인 정보 입력 시 적절한 에러 메시지가 표시되어야 한다"

  - type: textarea
    id: additional
    attributes:
      label: "추가 정보"
      description: "에러 로그, 스크린샷, 환경 정보 등"
      placeholder: |
        - 에러 로그
        - 스크린샷
        - 발생 시점
        - 콘솔 에러 메시지
        - 네트워크 상태 
