name: "이슈 생성"
description: |
  GitHub에서 이슈를 생성하면, 해당 이슈를 기반으로 브랜치를 생성하여 작업을 시작할 수 있습니다.

  ✅ 브랜치 이름은 아래 형식을 따라 주세요:
  → **feat/DTalks-123-기능이름**  
  → **fix/DTalks-124-버그수정**  
  → 예시: `feat/DTalks-101-login-page`, `refactor/DTalks-205-cleanup-code`

title: "이슈 이름을 작성해주세요"

body:
  - type: dropdown
    id: branchType
    attributes:
      label: "📂 브랜치 타입"
      description: "기능 타입을 선택하세요"
      options:
        - feat
        - fix
        - hotfix
        - refactor
        - test
        - add
    validations:
      required:
