name: Notify KakaoWork on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-kakaowork:
    runs-on: ubuntu-latest
    steps:
      - name: Notify KakaoWork on PR merge
        if: github.event.pull_request.merged == true
        run: |
          echo "카카오워크로 PR 머지 알림 전송 중"
          
          # 변수 설정
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          REPO_NAME="${{ github.repository }}"
          
          # PR 본문에서 이슈 번호 추출
          PR_BODY="${{ github.event.pull_request.body }}"
          ISSUE_NUMBERS=""
          
          if [ -n "$PR_BODY" ]; then
            ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oE "(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*#[0-9]+" | grep -oE "#[0-9]+" | sort -u | tr '\n' ', ' | sed 's/, $//')
          fi
          
          curl -X POST "${{ secrets.KAKAOWORK_WEBHOOK_URL }}" \
            -H 'Content-Type: application/json' \
            -d '{
              "text": "PR이 머지되었습니다 - '"$REPO_NAME"'",
              "blocks": [
                {
                  "type": "text",
                  "text": "✨ PR이 머지되었습니다.",
                  "markdown": true
                },
                {
                  "type": "text",
                  "text": "*리포지토리:* '"$REPO_NAME"'",
                  "markdown": true
                },
                {
                  "type": "text",
                  "text": "*PR:* ['"$PR_TITLE"']('"$PR_URL"')",
                  "markdown": true
                },
                {
                  "type": "text",
                  "text": "*이 PR로 닫힌 이슈:* '"$ISSUE_NUMBERS"'",
                  "markdown": true
                },
                {
                  "type": "text",
                  "text": "*PR 보기:* [클릭]('"$PR_URL"')",
                  "markdown": true
                }
              ]
            }' 
